// Generated by https://quicktype.io

export interface DataUser {
  nombre:          string;
  apellidoP:       string;
  apellidoM:       string;
  fechaNacimiento: string;
  sexo:            string;
  telefono:        string;
  correo:          string;
  usuario:         string;
}
