name: PWA CI/CD Workflow

# Configuración de los desencadenadores
on:
  # Ejecuta el workflow cuando hay un push a ramas específicas (e.g., master y main)
  push:
    branches:
      - master
      - main

  # Ejecuta el workflow cuando se crea o actualiza un pull request
  pull_request:
    branches:
      - master
      - main

  # Permite la ejecución manual del workflow (opcional)
  workflow_dispatch:

# Definición de los trabajos (jobs)
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4.2.1
      
      - name: Ejecutar un comando de ejemplo
        run: echo "Workflow activado correctamente"
