name: PWA CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout código
        uses: actions/checkout@v4

      # Paso 2: Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Paso 3: Instalar dependencias
      - name: Instalar dependencias
        run: npm install

      # Paso 4: Compilar el proyecto (ng build)
      - name: Compilar el proyecto
        run: ng build

      # Paso 5: Instalar Netlify CLI
      - name: Instalar Netlify CLI
        run: npm install -g netlify-cli

      # Paso 6: Desplegar en Netlify
      - name: Desplegar en Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          netlify deploy --prod --dir=dist/dental-front/browser --site=75df4072-c301-45aa-a441-03197b94cd06

